[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
socket2 = "0.5.7"
chrono = "0.4.38"
flate2 = "1.0.35"
argon2 = "0.5.3"
serde_json = "1.0.133"
serde = "1.0.215"
rand = "0.8.5"
colored = "2.2.0"
